@startuml
title biogenicCarbon
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class biogenicCarbon <<SMC>> {
  sem: Sem_102
}
class biogenicCarbonProduct <<Property>> {
  valueType: xs:decimal
  sem: Sem_103
}
class biogenicCarbonPackaging <<Property>> {
  valueType: xs:decimal
  sem: Sem_104
}

biogenicCarbon *-- "1" biogenicCarbonProduct
biogenicCarbon *-- "0..1" biogenicCarbonPackaging
@enduml