@startuml
title DeclaredUnit
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class DeclaredUnit <<SMC>> {
  sem: Sem_058
}
class quantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_055
}
class unit <<Property>> {
  valueType: xs:string
  sem: Sem_056
}
class description <<MLP>> {
  sem: Sem_057
}

DeclaredUnit *-- "1" quantity
DeclaredUnit *-- "1" unit
DeclaredUnit *-- "0..1" description
@enduml