@startuml
title declaredUnit
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class declaredUnit <<SMC>> {
  sem: Sem_029
}
class declaredQuantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_069
}
class unitOfMeasure <<Property>> {
  valueType: xs:string
  sem: Sem_070
}
class massPerDeclaredUnit <<Property>> {
  valueType: xs:decimal
  sem: Sem_032
}
class referenceServiceLife <<Property>> {
  valueType: xs:integer
  sem: Sem_033
}

declaredUnit *-- "1" declaredQuantity
declaredUnit *-- "1" unitOfMeasure
declaredUnit *-- "0..1" massPerDeclaredUnit
declaredUnit *-- "0..1" referenceServiceLife
@enduml