@startuml
title FunctionalUnit
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class FunctionalUnit <<SMC>> {
  sem: Sem_070
}
class quantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_071
}
class unit <<Property>> {
  valueType: xs:string
  sem: Sem_072
}
class description <<MLP>> {
  sem: Sem_073
}

FunctionalUnit *-- "1" quantity
FunctionalUnit *-- "1" unit
FunctionalUnit *-- "0..1" description
@enduml