@startuml
title FunctionalUnit
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class FunctionalUnit <<SMC>> {
  sem: Sem_054
}
class quantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_055
}
class unit <<Property>> {
  valueType: xs:string
  sem: Sem_056
}
class description <<MLP>> {
  sem: Sem_057
}

FunctionalUnit *-- "1" quantity
FunctionalUnit *-- "1" unit
FunctionalUnit *-- "0..1" description
@enduml