@startuml
title identificationPublication
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class identificationPublication <<SMC>> {
  sem: Sem_001
}
class documentIds <<SML>> {
  sem: Sem_002
}
class programOperatorVersion <<Property>> {
  valueType: xs:string
  sem: Sem_003
}
class dateOfIssue <<Property>> {
  valueType: xs:date
  sem: Sem_004
}
class validUntil <<Property>> {
  valueType: xs:date
  sem: Sem_005
}
class languages <<SML>> {
  sem: Sem_006
}
class sourceDataFormat <<Property>> {
  valueType: xs:string
  sem: Sem_007
}
class declarationUrl <<Property>> {
  valueType: xs:string
  sem: Sem_008
}

identificationPublication *-- "1" documentIds
identificationPublication *-- "1" programOperatorVersion
identificationPublication *-- "1" dateOfIssue
identificationPublication *-- "1" validUntil
identificationPublication *-- "1" languages
identificationPublication *-- "0..1" sourceDataFormat
identificationPublication *-- "0..1" declarationUrl
@enduml