@startuml
title lca_StandardsPcr
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class lca_StandardsPcr <<SMC>> {
  sem: Sem_052
}
class standardsCompliance <<SML>> {
  sem: Sem_053
}
class productCategoryRules <<SML>> {
  sem: Sem_054
}

lca_StandardsPcr *-- "1" standardsCompliance
lca_StandardsPcr *-- "1" productCategoryRules
@enduml