@startuml
title lca_StandardsPcr
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class lca_StandardsPcr <<SMC>> {
  sem: Sem_064
}
class pcr.id <<Property>> {
  valueType: xs:string
  sem: Sem_065
}
class pcr.name <<Property>> {
  valueType: xs:string
  sem: Sem_066
}
class compliance <<Property>> {
  valueType: xs:string
  sem: Sem_067
}
class lcaDiscussion <<Property>> {
  valueType: xs:string
  sem: Sem_068
}
class pcr.publisher <<Property>> {
  valueType: xs:string
  sem: Sem_069
}
class pcr.referenceYear <<Property>> {
  valueType: xs:string
  sem: Sem_070
}
class pcr.link <<Property>> {
  valueType: xs:string
  sem: Sem_071
}
class pcr.version <<Property>> {
  valueType: xs:string
  sem: Sem_072
}
class pcr.validFrom <<Property>> {
  valueType: xs:date
  sem: Sem_073
}
class pcr.validUntil <<Property>> {
  valueType: xs:date
  sem: Sem_074
}

lca_StandardsPcr *-- "1" pcr.id
lca_StandardsPcr *-- "1" pcr.name
lca_StandardsPcr *-- "1" compliance
lca_StandardsPcr *-- "1" lcaDiscussion
lca_StandardsPcr *-- "1" pcr.publisher
lca_StandardsPcr *-- "1" pcr.referenceYear
lca_StandardsPcr *-- "1" pcr.link
lca_StandardsPcr *-- "1" pcr.version
lca_StandardsPcr *-- "1" pcr.validFrom
lca_StandardsPcr *-- "1" pcr.validUntil
@enduml