@startuml
title LCAMethodology
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class LCAMethodology <<SMC>> {
  sem: Sem_029
}
class referenceYear <<Property>> {
  valueType: xs:string
  sem: Sem_030
}
class dataSetValidUntil <<Property>> {
  valueType: xs:string
  sem: Sem_031
}
class timeRepresentativenessDescription <<Property>> {
  valueType: xs:string
  sem: Sem_032
}
class location <<Property>> {
  valueType: xs:string
  sem: Sem_033
}
class geographicalDescription <<Property>> {
  valueType: xs:string
  sem: Sem_034
}
class technologyDescription <<Property>> {
  valueType: xs:string
  sem: Sem_035
}
class technicalPurpose <<Property>> {
  valueType: xs:string
  sem: Sem_036
}
class energyModel <<Property>> {
  valueType: xs:string
  sem: Sem_037
}
class DeclaredStages <<SML>> {
  sem: Sem_038
}

LCAMethodology *-- "1" referenceYear
LCAMethodology *-- "1" dataSetValidUntil
LCAMethodology *-- "1" timeRepresentativenessDescription
LCAMethodology *-- "1" location
LCAMethodology *-- "1" geographicalDescription
LCAMethodology *-- "1" technologyDescription
LCAMethodology *-- "1" technicalPurpose
LCAMethodology *-- "0..1" energyModel
LCAMethodology *-- "1" DeclaredStages
@enduml