@startuml
title lciaResults
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class lciaResults <<SML>> {
  sem: Sem_055
}
class None <<SMC>> {
  sem: Sem_056
}
class lciaIndicator <<SMC>> {
  sem: Sem_057
}
class indicatorCode <<Property>> {
  valueType: xs:string
  sem: Sem_058
}
class indicatorName <<Property>> {
  valueType: xs:string
  sem: Sem_059
}
class indicatorGroup <<Property>> {
  valueType: xs:string
  sem: Sem_060
}
class indicatorStandard <<Property>> {
  valueType: xs:string
  sem: Sem_061
}
class characterizationUnit <<SMC>> {
  sem: Sem_062
}
class unit <<Property>> {
  valueType: xs:string
}
class unitId <<Property>> {
  valueType: xs:string
}
class baseUnit <<SMC>> {
}
class unit <<Property>> {
  valueType: xs:string
}
class unitId <<Property>> {
  valueType: xs:string
}
class referenceUnitForCalculation <<Property>> {
  valueType: xs:string
  sem: Sem_063
}
class quantityOfReferenceUnit <<Property>> {
  valueType: xs:decimal
  sem: Sem_064
}
class lifeCyclePhaseValues <<SML>> {
  sem: Sem_065
}
class None <<SMC>> {
  sem: Sem_066
}
class lifeCyclePhase <<Property>> {
  valueType: xs:string
  sem: Sem_067
}
class value <<Property>> {
  valueType: xs:decimal
  sem: Sem_068
}

lciaResults *-- "0..*" None
None *-- "1" lciaIndicator
lciaIndicator *-- "1" indicatorCode
lciaIndicator *-- "1" indicatorName
lciaIndicator *-- "1" indicatorGroup
lciaIndicator *-- "0..1" indicatorStandard
None *-- "1" characterizationUnit
characterizationUnit *-- "1" unit
characterizationUnit *-- "1" unitId
characterizationUnit *-- "0..1" baseUnit
baseUnit *-- "1" unit
baseUnit *-- "1" unitId
None *-- "0..1" referenceUnitForCalculation
None *-- "0..1" quantityOfReferenceUnit
None *-- "1" lifeCyclePhaseValues
lifeCyclePhaseValues *-- "0..*" None
None *-- "1" lifeCyclePhase
None *-- "1" value
@enduml