@startuml
title manufacturerProduct
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class manufacturerProduct <<SMC>> {
  sem: Sem_018
}
class manufacturerName <<MLP>> {
  sem: Sem_019
}
class manufacturingSites <<SML>> {
  sem: Sem_020
}
class productName <<MLP>> {
  sem: Sem_021
}
class productArticleNumberOfManufacturer <<Property>> {
  valueType: xs:string
  sem: Sem_022
}
class productDescription <<MLP>> {
  sem: Sem_023
}
class productImage <<File>> {
  sem: Sem_024
}
class massPerDeclaredUnit <<Property>> {
  valueType: xs:decimal
  sem: Sem_025
}
class referenceServiceLife <<Property>> {
  valueType: xs:decimal
  sem: Sem_026
}
class applicableJurisdictions <<SML>> {
  sem: Sem_027
}
class manufacturingDescription <<MLP>> {
  sem: Sem_028
}

manufacturerProduct *-- "1" manufacturerName
manufacturerProduct *-- "0..1" manufacturingSites
manufacturerProduct *-- "1" productName
manufacturerProduct *-- "1" productArticleNumberOfManufacturer
manufacturerProduct *-- "0..1" productDescription
manufacturerProduct *-- "0..1" productImage
manufacturerProduct *-- "0..1" massPerDeclaredUnit
manufacturerProduct *-- "0..1" referenceServiceLife
manufacturerProduct *-- "0..1" applicableJurisdictions
manufacturerProduct *-- "0..1" manufacturingDescription
@enduml