@startuml
title programOperatorVerification
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

class programOperatorVerification <<SMC>> {
  sem: Sem_009
}
class programOperator <<SMC>> {
  sem: Sem_010
}
class Company <<Property>> {
  valueType: xs:string
  sem: Sem_011
}
class EmailAddress <<SMC>> {
  sem: Sem_012
}
class EmailAddress <<Property>> {
  valueType: xs:string
  sem: Sem_013
}
class thirdPartyVerifier <<SMC>> {
  sem: Sem_010
}
class verifierAccreditationId <<Property>> {
  valueType: xs:string
  sem: Sem_014
}
class epdDeveloper <<SMC>> {
  sem: Sem_010
}
class Company <<MLP>> {
  sem: Sem_015
}
class verificationType <<Property>> {
  valueType: xs:string
  sem: Sem_016
}
class verificationDate <<Property>> {
  valueType: xs:date
  sem: Sem_017
}

programOperatorVerification *-- "1" programOperator
programOperator *-- "0..*" Company
programOperator *-- "0..*" EmailAddress
EmailAddress *-- "1" EmailAddress
programOperatorVerification *-- "0..1" thirdPartyVerifier
thirdPartyVerifier *-- "0..1" verifierAccreditationId
programOperatorVerification *-- "0..1" epdDeveloper
epdDeveloper *-- "1" Company
programOperatorVerification *-- "0..1" verificationType
programOperatorVerification *-- "0..1" verificationDate
@enduml