@startuml
title EPD Type III Model
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

package "identificationPublication" {
class identificationPublication <<SMC>> {
  sem: Sem_001
}
class documentIds <<SML>> {
  sem: Sem_002
}
class documentId_01 <<SMC>> {
  sem: Sem_003
}
class documentDomainId <<Property>> {
  valueType: xs:string
  sem: Sem_004
}
class documentIdentifier <<Property>> {
  valueType: xs:string
  sem: Sem_005
}
class documentIsPrimary <<Property>> {
  valueType: xs:boolean
  sem: Sem_006
}
class programOperatorVersion <<Property>> {
  valueType: xs:string
  sem: Sem_007
}
class dateOfIssue <<Property>> {
  valueType: xs:date
  sem: Sem_008
}
class validUntil <<Property>> {
  valueType: xs:date
  sem: Sem_009
}
class languages <<SML>> {
  sem: Sem_010
}
class language_01 <<Property>> {
  valueType: xs:string
  sem: Sem_011
}
class sourceDataFormat <<Property>> {
  valueType: xs:string
  sem: Sem_012
}
class declarationUrl <<Property>> {
  valueType: xs:string
  sem: Sem_013
}
}
package "programOperatorVerification" {
class programOperatorVerification <<SMC>> {
  sem: Sem_014
}
class programOperator <<SMC>> {
  sem: Sem_015
}
class Company <<Property>> {
  valueType: xs:string
  sem: Sem_016
}
class EmailAddress <<SMC>> {
  sem: Sem_017
}
class EmailAddress <<Property>> {
  valueType: xs:string
  sem: Sem_018
}
class thirdPartyVerifier <<SMC>> {
  sem: Sem_015
}
class verifierAccreditationId <<Property>> {
  valueType: xs:string
  sem: Sem_019
}
class verificationStatementUrl <<Property>> {
  valueType: xs:string
  sem: Sem_020
}
class epdDeveloper <<SMC>> {
  sem: Sem_015
}
class Company <<MLP>> {
  sem: Sem_021
}
}
package "manufacturerProduct" {
class manufacturerProduct <<SMC>> {
  sem: Sem_022
}
class manufacturerName <<MLP>> {
  sem: Sem_023
}
class manufacturingSites <<SML>> {
  sem: Sem_024
}
class productName <<MLP>> {
  sem: Sem_025
}
class productArticleNumberOfManufacturer <<Property>> {
  valueType: xs:string
  sem: Sem_026
}
class productDescription <<MLP>> {
  sem: Sem_027
}
class productImage <<File>> {
  sem: Sem_028
}
class declaredUnit <<SMC>> {
  sem: Sem_029
}
class quantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_030
}
class unit <<Property>> {
  valueType: xs:string
  sem: Sem_031
}
class massPerDeclaredUnit <<Property>> {
  valueType: xs:decimal
  sem: Sem_032
}
class referenceServiceLife <<Property>> {
  valueType: xs:decimal
  sem: Sem_033
}
class applicableJurisdictions <<SML>> {
  sem: Sem_034
}
class manufacturingDescription <<MLP>> {
  sem: Sem_035
}
class biogenicCarbonContent <<SMC>> {
  sem: Sem_036
}
class biogenicCarbonContentProduct <<Property>> {
  valueType: xs:decimal
  sem: Sem_037
}
class biogenicCarbonContentPackaging <<Property>> {
  valueType: xs:decimal
  sem: Sem_038
}
}
package "representativenessReference" {
class representativenessReference <<SMC>> {
  sem: Sem_039
}
class referenceFlow.id <<Property>> {
  valueType: xs:string
  sem: Sem_040
}
class referenceFlow.amount <<Property>> {
  valueType: xs:string
  sem: Sem_041
}
class referenceYear <<Property>> {
  valueType: xs:string
  sem: Sem_042
}
class dataSetValidUntil <<Property>> {
  valueType: xs:string
  sem: Sem_043
}
class timeRepresentativenessDescription <<Property>> {
  valueType: xs:string
  sem: Sem_044
}
class location <<Property>> {
  valueType: xs:string
  sem: Sem_045
}
class geographicalDescription <<Property>> {
  valueType: xs:string
  sem: Sem_046
}
class technologyDescription <<Property>> {
  valueType: xs:string
  sem: Sem_047
}
class technicalPurpose <<Property>> {
  valueType: xs:string
  sem: Sem_048
}
class pictogramSource <<Property>> {
  valueType: xs:string
  sem: Sem_049
}
class flowDiagramSource <<Property>> {
  valueType: xs:string
  sem: Sem_050
}
class energyModel <<Property>> {
  valueType: xs:string
  sem: Sem_051
}
}
package "lca_StandardsPcr" {
class lca_StandardsPcr <<SMC>> {
  sem: Sem_052
}
class pcr.id <<Property>> {
  valueType: xs:string
  sem: Sem_053
}
class pcr.name <<Property>> {
  valueType: xs:string
  sem: Sem_054
}
class compliance <<Property>> {
  valueType: xs:string
  sem: Sem_055
}
class lcaDiscussion <<Property>> {
  valueType: xs:string
  sem: Sem_056
}
class pcr.publisher <<Property>> {
  valueType: xs:string
  sem: Sem_057
}
class pcr.referenceYear <<Property>> {
  valueType: xs:string
  sem: Sem_058
}
class pcr.link <<Property>> {
  valueType: xs:string
  sem: Sem_059
}
class pcr.version <<Property>> {
  valueType: xs:string
  sem: Sem_060
}
class pcr.validFrom <<Property>> {
  valueType: xs:date
  sem: Sem_061
}
class pcr.validUntil <<Property>> {
  valueType: xs:date
  sem: Sem_062
}
}
package "lciaResults" {
class lciaResults <<SML>> {
  sem: Sem_063
}
class None <<SMC>> {
  sem: Sem_064
}
class lciaIndicator <<SMC>> {
  sem: Sem_065
}
class indicatorCode <<Property>> {
  valueType: xs:string
  sem: Sem_066
}
class indicatorName <<Property>> {
  valueType: xs:string
  sem: Sem_067
}
class indicatorGroup <<Property>> {
  valueType: xs:string
  sem: Sem_068
}
class indicatorStandard <<Property>> {
  valueType: xs:string
  sem: Sem_069
}
class characterizationUnit <<SMC>> {
  sem: Sem_070
}
class unit <<Property>> {
  valueType: xs:string
}
class unitId <<Property>> {
  valueType: xs:string
}
class baseUnit <<SMC>> {
}
class unit <<Property>> {
  valueType: xs:string
}
class unitId <<Property>> {
  valueType: xs:string
}
class referenceUnitForCalculation <<Property>> {
  valueType: xs:string
  sem: Sem_071
}
class quantityOfReferenceUnit <<Property>> {
  valueType: xs:decimal
  sem: Sem_072
}
class lifeCyclePhaseValues <<SML>> {
  sem: Sem_073
}
class None <<SMC>> {
  sem: Sem_074
}
class lifeCyclePhase <<Property>> {
  valueType: xs:string
  sem: Sem_075
}
class value <<Property>> {
  valueType: xs:decimal
  sem: Sem_076
}
}
package "declaredUnit" {
class declaredUnit <<SMC>> {
  sem: Sem_029
}
class declaredQuantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_077
}
class unitOfMeasure <<Property>> {
  valueType: xs:string
  sem: Sem_078
}
class massPerDeclaredUnit <<Property>> {
  valueType: xs:decimal
  sem: Sem_032
}
class referenceServiceLife <<Property>> {
  valueType: xs:integer
  sem: Sem_033
}
}
package "systemBoundary" {
class systemBoundary <<SMC>> {
  sem: Sem_079
}
class includesA1_A3 <<Property>> {
  valueType: xs:boolean
  sem: Sem_080
}
class includesA4_A5 <<Property>> {
  valueType: xs:boolean
  sem: Sem_081
}
class includesB1_B7 <<Property>> {
  valueType: xs:boolean
  sem: Sem_082
}
class includesC1_C4 <<Property>> {
  valueType: xs:boolean
  sem: Sem_083
}
class includesD <<Property>> {
  valueType: xs:boolean
  sem: Sem_084
}
class geographicScope <<Property>> {
  valueType: xs:string
  sem: Sem_085
}
class technologyCoverage <<Property>> {
  valueType: xs:string
  sem: Sem_086
}
}
package "epdDocument" {
class epdDocument <<File>> {
  sem: Sem_087
}
}

identificationPublication *-- "1" documentIds
documentIds *-- "1..*" documentId_01
documentId_01 *-- "1" documentDomainId
documentId_01 *-- "1" documentIdentifier
documentId_01 *-- "0..1" documentIsPrimary
identificationPublication *-- "1" programOperatorVersion
identificationPublication *-- "1" dateOfIssue
identificationPublication *-- "1" validUntil
identificationPublication *-- "1" languages
languages *-- "1..*" language_01
identificationPublication *-- "0..1" sourceDataFormat
identificationPublication *-- "0..1" declarationUrl
programOperatorVerification *-- "1" programOperator
programOperator *-- "0..*" Company
programOperator *-- "0..*" EmailAddress
EmailAddress *-- "1" EmailAddress
programOperatorVerification *-- "0..1" thirdPartyVerifier
thirdPartyVerifier *-- "0..1" verifierAccreditationId
thirdPartyVerifier *-- "0..1" verificationStatementUrl
programOperatorVerification *-- "0..1" epdDeveloper
epdDeveloper *-- "1" Company
manufacturerProduct *-- "1" manufacturerName
manufacturerProduct *-- "0..1" manufacturingSites
manufacturerProduct *-- "1" productName
manufacturerProduct *-- "1" productArticleNumberOfManufacturer
manufacturerProduct *-- "0..1" productDescription
manufacturerProduct *-- "0..1" productImage
manufacturerProduct *-- "1" declaredUnit
declaredUnit *-- "1" quantity
declaredUnit *-- "1" unit
manufacturerProduct *-- "0..1" massPerDeclaredUnit
manufacturerProduct *-- "0..1" referenceServiceLife
manufacturerProduct *-- "0..1" applicableJurisdictions
manufacturerProduct *-- "0..1" manufacturingDescription
manufacturerProduct *-- "0..1" biogenicCarbonContent
biogenicCarbonContent *-- "0..1" biogenicCarbonContentProduct
biogenicCarbonContent *-- "0..1" biogenicCarbonContentPackaging
representativenessReference *-- "1" referenceFlow.id
representativenessReference *-- "1" referenceFlow.amount
representativenessReference *-- "1" referenceYear
representativenessReference *-- "1" dataSetValidUntil
representativenessReference *-- "1" timeRepresentativenessDescription
representativenessReference *-- "1" location
representativenessReference *-- "1" geographicalDescription
representativenessReference *-- "1" technologyDescription
representativenessReference *-- "1" technicalPurpose
representativenessReference *-- "1" pictogramSource
representativenessReference *-- "1" flowDiagramSource
representativenessReference *-- "0..1" energyModel
lca_StandardsPcr *-- "1" pcr.id
lca_StandardsPcr *-- "1" pcr.name
lca_StandardsPcr *-- "1" compliance
lca_StandardsPcr *-- "1" lcaDiscussion
lca_StandardsPcr *-- "1" pcr.publisher
lca_StandardsPcr *-- "1" pcr.referenceYear
lca_StandardsPcr *-- "1" pcr.link
lca_StandardsPcr *-- "1" pcr.version
lca_StandardsPcr *-- "1" pcr.validFrom
lca_StandardsPcr *-- "1" pcr.validUntil
lciaResults *-- "0..*" None
None *-- "1" lciaIndicator
lciaIndicator *-- "1" indicatorCode
lciaIndicator *-- "1" indicatorName
lciaIndicator *-- "1" indicatorGroup
lciaIndicator *-- "0..1" indicatorStandard
None *-- "1" characterizationUnit
characterizationUnit *-- "1" unit
characterizationUnit *-- "1" unitId
characterizationUnit *-- "0..1" baseUnit
baseUnit *-- "1" unit
baseUnit *-- "1" unitId
None *-- "0..1" referenceUnitForCalculation
None *-- "0..1" quantityOfReferenceUnit
None *-- "1" lifeCyclePhaseValues
lifeCyclePhaseValues *-- "0..*" None
None *-- "1" lifeCyclePhase
None *-- "1" value
declaredUnit *-- "1" declaredQuantity
declaredUnit *-- "1" unitOfMeasure
declaredUnit *-- "0..1" massPerDeclaredUnit
declaredUnit *-- "0..1" referenceServiceLife
systemBoundary *-- "1" includesA1_A3
systemBoundary *-- "0..1" includesA4_A5
systemBoundary *-- "0..1" includesB1_B7
systemBoundary *-- "0..1" includesC1_C4
systemBoundary *-- "0..1" includesD
systemBoundary *-- "1" geographicScope
systemBoundary *-- "0..1" technologyCoverage
@enduml