@startuml
title EPD Type III Model
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

package "identificationPublication" {
class identificationPublication <<SMC>> {
  sem: Sem_001
}
class documentIds <<SML>> {
  sem: Sem_002
}
class documentId_01 <<SMC>> {
  sem: Sem_003
}
class documentDomainId <<Property>> {
  valueType: xs:string
  sem: Sem_004
}
class documentIdentifier <<Property>> {
  valueType: xs:string
  sem: Sem_005
}
class documentIsPrimary <<Property>> {
  valueType: xs:boolean
  sem: Sem_006
}
class programOperatorVersion <<Property>> {
  valueType: xs:string
  sem: Sem_007
}
class dateOfIssue <<Property>> {
  valueType: xs:date
  sem: Sem_008
}
class validUntil <<Property>> {
  valueType: xs:date
  sem: Sem_009
}
class languages <<SML>> {
  sem: Sem_010
}
class language_01 <<Property>> {
  valueType: xs:string
  sem: Sem_011
}
class sourceDataFormat <<Property>> {
  valueType: xs:string
  sem: Sem_012
}
class declarationUrl <<Property>> {
  valueType: xs:string
  sem: Sem_013
}
}
package "programOperatorVerification" {
class programOperatorVerification <<SMC>> {
  sem: Sem_014
}
class programOperator <<SMC>> {
  sem: Sem_015
}
class Company <<Property>> {
  valueType: xs:string
  sem: Sem_016
}
class EmailAddress <<SMC>> {
  sem: Sem_017
}
class EmailAddress <<Property>> {
  valueType: xs:string
  sem: Sem_018
}
class thirdPartyVerifier <<SMC>> {
  sem: Sem_015
}
class verifierAccreditationId <<Property>> {
  valueType: xs:string
  sem: Sem_019
}
class verificationStatementUrl <<Property>> {
  valueType: xs:string
  sem: Sem_020
}
class epdDeveloper <<SMC>> {
  sem: Sem_015
}
class Company <<MLP>> {
  sem: Sem_021
}
class verificationType <<Property>> {
  valueType: xs:string
  sem: Sem_022
}
class verificationDate <<Property>> {
  valueType: xs:date
  sem: Sem_023
}
}
package "manufacturerProduct" {
class manufacturerProduct <<SMC>> {
  sem: Sem_024
}
class manufacturerName <<MLP>> {
  sem: Sem_025
}
class manufacturingSites <<SML>> {
  sem: Sem_026
}
class productName <<MLP>> {
  sem: Sem_027
}
class productArticleNumberOfManufacturer <<Property>> {
  valueType: xs:string
  sem: Sem_028
}
class productDescription <<MLP>> {
  sem: Sem_029
}
class productImage <<File>> {
  sem: Sem_030
}
class declaredUnit <<SMC>> {
  sem: Sem_031
}
class quantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_032
}
class unit <<Property>> {
  valueType: xs:string
  sem: Sem_033
}
class massPerDeclaredUnit <<Property>> {
  valueType: xs:decimal
  sem: Sem_034
}
class referenceServiceLife <<Property>> {
  valueType: xs:decimal
  sem: Sem_035
}
class applicableJurisdictions <<SML>> {
  sem: Sem_036
}
class manufacturingDescription <<MLP>> {
  sem: Sem_037
}
class biogenicCarbonContent <<SMC>> {
  sem: Sem_038
}
class biogenicCarbonContentProduct <<Property>> {
  valueType: xs:decimal
  sem: Sem_039
}
class biogenicCarbonContentPackaging <<Property>> {
  valueType: xs:decimal
  sem: Sem_040
}
}
package "LCAMethodology" {
class LCAMethodology <<SMC>> {
  sem: Sem_041
}
class referenceFlow.id <<Property>> {
  valueType: xs:string
  sem: Sem_042
}
class referenceFlow.amount <<Property>> {
  valueType: xs:string
  sem: Sem_043
}
class referenceYear <<Property>> {
  valueType: xs:string
  sem: Sem_044
}
class dataSetValidUntil <<Property>> {
  valueType: xs:string
  sem: Sem_045
}
class timeRepresentativenessDescription <<Property>> {
  valueType: xs:string
  sem: Sem_046
}
class location <<Property>> {
  valueType: xs:string
  sem: Sem_047
}
class geographicalDescription <<Property>> {
  valueType: xs:string
  sem: Sem_048
}
class technologyDescription <<Property>> {
  valueType: xs:string
  sem: Sem_049
}
class technicalPurpose <<Property>> {
  valueType: xs:string
  sem: Sem_050
}
class pictogramSource <<Property>> {
  valueType: xs:string
  sem: Sem_051
}
class flowDiagramSource <<Property>> {
  valueType: xs:string
  sem: Sem_052
}
class energyModel <<Property>> {
  valueType: xs:string
  sem: Sem_053
}
class DeclaredStages <<SML>> {
  sem: Sem_054
}
}
package "lca_StandardsPcr" {
class lca_StandardsPcr <<SMC>> {
  sem: Sem_055
}
class standardsCompliance <<SML>> {
  sem: Sem_056
}
class productCategoryRules <<SML>> {
  sem: Sem_057
}
}
package "epdDocument" {
class epdDocument <<File>> {
  sem: Sem_058
}
}
package "EnvironmentalResults" {
class EnvironmentalResults <<SML>> {
  sem: Sem_059
}
}
package "EPDScope" {
class EPDScope <<SMC>> {
  sem: Sem_060
}
class scopeType <<Property>> {
  valueType: xs:string
  sem: Sem_061
}
class coveredProductReferences <<SML>> {
  sem: Sem_062
}
class scopeDescription <<MLP>> {
  sem: Sem_063
}
class sourceDeclarationReference <<Property>> {
  valueType: xs:string
  sem: Sem_064
}
}
package "ContentDeclaration" {
class ContentDeclaration <<SMC>> {
  sem: Sem_065
}
class productMass <<Property>> {
  valueType: xs:decimal
  sem: Sem_066
}
class biogenicCarbonContentProduct <<Property>> {
  valueType: xs:decimal
  sem: Sem_067
}
class biogenicCarbonContentPackaging <<Property>> {
  valueType: xs:decimal
  sem: Sem_068
}
class recycledContentPercentage <<Property>> {
  valueType: xs:decimal
  sem: Sem_069
}
}
package "FunctionalUnit" {
class FunctionalUnit <<SMC>> {
  sem: Sem_070
}
class quantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_071
}
class unit <<Property>> {
  valueType: xs:string
  sem: Sem_072
}
class description <<MLP>> {
  sem: Sem_073
}
}
package "DeclaredUnit" {
class DeclaredUnit <<SMC>> {
  sem: Sem_074
}
class quantity <<Property>> {
  valueType: xs:decimal
  sem: Sem_071
}
class unit <<Property>> {
  valueType: xs:string
  sem: Sem_072
}
class description <<MLP>> {
  sem: Sem_073
}
}

identificationPublication *-- "1" documentIds
documentIds *-- "1..*" documentId_01
documentId_01 *-- "1" documentDomainId
documentId_01 *-- "1" documentIdentifier
documentId_01 *-- "0..1" documentIsPrimary
identificationPublication *-- "1" programOperatorVersion
identificationPublication *-- "1" dateOfIssue
identificationPublication *-- "1" validUntil
identificationPublication *-- "1" languages
languages *-- "1..*" language_01
identificationPublication *-- "0..1" sourceDataFormat
identificationPublication *-- "0..1" declarationUrl
programOperatorVerification *-- "1" programOperator
programOperator *-- "0..*" Company
programOperator *-- "0..*" EmailAddress
EmailAddress *-- "1" EmailAddress
programOperatorVerification *-- "0..1" thirdPartyVerifier
thirdPartyVerifier *-- "0..1" verifierAccreditationId
thirdPartyVerifier *-- "0..1" verificationStatementUrl
programOperatorVerification *-- "0..1" epdDeveloper
epdDeveloper *-- "1" Company
programOperatorVerification *-- "0..1" verificationType
programOperatorVerification *-- "0..1" verificationDate
manufacturerProduct *-- "1" manufacturerName
manufacturerProduct *-- "0..1" manufacturingSites
manufacturerProduct *-- "1" productName
manufacturerProduct *-- "1" productArticleNumberOfManufacturer
manufacturerProduct *-- "0..1" productDescription
manufacturerProduct *-- "0..1" productImage
manufacturerProduct *-- "1" declaredUnit
declaredUnit *-- "1" quantity
declaredUnit *-- "1" unit
manufacturerProduct *-- "0..1" massPerDeclaredUnit
manufacturerProduct *-- "0..1" referenceServiceLife
manufacturerProduct *-- "0..1" applicableJurisdictions
manufacturerProduct *-- "0..1" manufacturingDescription
manufacturerProduct *-- "0..1" biogenicCarbonContent
biogenicCarbonContent *-- "0..1" biogenicCarbonContentProduct
biogenicCarbonContent *-- "0..1" biogenicCarbonContentPackaging
LCAMethodology *-- "1" referenceFlow.id
LCAMethodology *-- "1" referenceFlow.amount
LCAMethodology *-- "1" referenceYear
LCAMethodology *-- "1" dataSetValidUntil
LCAMethodology *-- "1" timeRepresentativenessDescription
LCAMethodology *-- "1" location
LCAMethodology *-- "1" geographicalDescription
LCAMethodology *-- "1" technologyDescription
LCAMethodology *-- "1" technicalPurpose
LCAMethodology *-- "1" pictogramSource
LCAMethodology *-- "1" flowDiagramSource
LCAMethodology *-- "0..1" energyModel
LCAMethodology *-- "1" DeclaredStages
lca_StandardsPcr *-- "1" standardsCompliance
lca_StandardsPcr *-- "1" productCategoryRules
EPDScope *-- "1" scopeType
EPDScope *-- "0..1" coveredProductReferences
EPDScope *-- "0..1" scopeDescription
EPDScope *-- "0..1" sourceDeclarationReference
ContentDeclaration *-- "0..1" productMass
ContentDeclaration *-- "0..1" biogenicCarbonContentProduct
ContentDeclaration *-- "0..1" biogenicCarbonContentPackaging
ContentDeclaration *-- "0..1" recycledContentPercentage
FunctionalUnit *-- "1" quantity
FunctionalUnit *-- "1" unit
FunctionalUnit *-- "0..1" description
DeclaredUnit *-- "1" quantity
DeclaredUnit *-- "1" unit
DeclaredUnit *-- "0..1" description
@enduml